//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OasisComp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdTable
    {
        public int ProdID { get; set; }
        public string ProdName { get; set; }
        public string ProdDesc { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> ProdPrice { get; set; }
    }
}
